from __future__ import annotations

"""
通用工具函数集合。

当前只放了最基础的状态合并函数；
后续可扩展为：
- 文本清洗；
- JSON 安全解析；
- 日志格式化；
- 重试与退避策略等。
"""

import json
import os
import re
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel

load_dotenv()


def merge_state(base: dict[str, Any], updates: dict[str, Any]) -> dict[str, Any]:
    """
    以浅合并方式合并两个字典。

    规则：
    - 先复制 base；
    - 再用 updates 覆盖同名键；
    - 返回新字典，不原地修改入参。

    适用场景：
    - 节点返回了部分状态更新，需要和旧状态拼接时。
    """
    merged = dict(base)
    merged.update(updates)
    return merged


def generate_with_outlines(
    *,
    prompt: str,
    output_model: type[BaseModel],
    fallback_data: dict[str, Any],
    model_name: str = "",
) -> tuple[dict[str, Any], bool, str]:
    """
    使用结构化生成能力产出 JSON。

    返回：
    - data: 结构化字典（可直接写入状态）
    - used_llm: 是否成功使用了 LLM
    - note: 说明信息（用于日志/调试）

    说明：
    - 优先尝试 Outlines；
    - 若 Outlines 不兼容当前提供商，则回退到 OpenAI-compatible SDK；
    - 当前已兼容 OpenAI 与 DeepSeek。
    """
    llm_settings = resolve_llm_settings(model_name=model_name)
    if not llm_settings["api_key"]:
        return fallback_data, False, "no supported API key found, fallback used"

    try:
        # outlines 在不同版本下 API 可能有细微差异，这里做兼容式调用。
        import outlines

        model = outlines.models.openai(
            llm_settings["model_name"],
            api_key=llm_settings["api_key"],
            base_url=llm_settings["base_url"],
        )
        generator = outlines.generate.json(model, output_model)
        result = generator(prompt)

        if isinstance(result, BaseModel):
            return result.model_dump(), True, f"generated by outlines ({llm_settings['provider']})"
        if isinstance(result, dict):
            parsed = output_model(**result)
            return parsed.model_dump(), True, f"generated by outlines ({llm_settings['provider']})"

        parsed = output_model.model_validate(result)
        return parsed.model_dump(), True, f"generated by outlines ({llm_settings['provider']})"
    except Exception as exc:  # noqa: BLE001
        outlines_error = str(exc)

    try:
        client = OpenAI(
            api_key=llm_settings["api_key"],
            base_url=llm_settings["base_url"],
        )
        # Build a simple field template instead of the full JSON Schema to avoid confusing small models.
        # Use actual JSON types ([], true, 0) so the model produces correctly typed values.
        import typing
        field_defaults: dict[str, Any] = {}
        for field_name, field_info in output_model.model_fields.items():
            annotation = field_info.annotation
            origin = getattr(annotation, "__origin__", None)
            if annotation is str or annotation == "str":
                field_defaults[field_name] = "..."
            elif annotation is bool or annotation == "bool":
                field_defaults[field_name] = True
            elif annotation is int or annotation == "int":
                field_defaults[field_name] = 0
            elif origin is list or annotation is list:
                field_defaults[field_name] = []
            else:
                field_defaults[field_name] = []
        template_example = json.dumps(field_defaults, ensure_ascii=False)
        messages = [
            {
                "role": "system",
                "content": (
                    "You are a structured output assistant. "
                    "Respond with ONLY a valid JSON object — no markdown, no code fences, no extra text. "
                    "Start your response with { and end with }. "
                    "Escape newlines in string values as \\n."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Task:\n{prompt}\n\n"
                    f"Respond with ONLY a JSON object matching this template "
                    f"(fill in actual values, keep the same keys):\n{template_example}"
                ),
            },
        ]
        # 优先尝试 json_object 模式（部分 OpenAI-compatible 提供商支持）。
        # max_tokens=1024 prevents models from padding response with thousands of whitespace chars.
        try:
            response = client.chat.completions.create(
                model=llm_settings["model_name"],
                messages=messages,
                stream=False,
                temperature=0,
                max_tokens=1024,
                response_format={"type": "json_object"},
            )
        except Exception:
            response = client.chat.completions.create(
                model=llm_settings["model_name"],
                messages=messages,
                stream=False,
                temperature=0,
                max_tokens=1024,
            )
        content = response.choices[0].message.content or ""
        parsed_json = _extract_json_object(content)
        # If the model used wrong key names (e.g. "find" instead of "code"),
        # try to rescue by promoting any Python-looking value to "code".
        if "code" in output_model.model_fields and "code" not in parsed_json:
            _PY_STARTERS = ("def ", "import ", "class ", "from ", "async def ", "#")
            for _val in parsed_json.values():
                if isinstance(_val, str) and any(_val.lstrip().startswith(s) for s in _PY_STARTERS):
                    parsed_json["code"] = _val
                    break
        parsed = output_model(**parsed_json)
        return (
            parsed.model_dump(),
            True,
            f"generated by openai-compatible sdk ({llm_settings['provider']})",
        )
    except Exception as exc:  # noqa: BLE001
        return (
            fallback_data,
            False,
            f"outlines failed: {outlines_error}; sdk fallback failed: {exc}",
        )


def resolve_llm_settings(model_name: str = "") -> dict[str, str]:
    """
    统一解析当前实验使用的模型提供商配置。

    优先级：
    1. SiliconFlow（硅基流动）环境变量
    2. DeepSeek 环境变量
    3. OpenAI 环境变量
    """
    if os.getenv("SILICONFLOW_API_KEY"):
        return {
            "provider": "siliconflow",
            "api_key": os.getenv("SILICONFLOW_API_KEY", ""),
            "base_url": os.getenv("SILICONFLOW_BASE_URL", "https://api.siliconflow.cn/v1"),
            "model_name": model_name or os.getenv("SILICONFLOW_MODEL", "Qwen/Qwen2.5-7B-Instruct"),
        }

    if os.getenv("DEEPSEEK_API_KEY"):
        return {
            "provider": "deepseek",
            "api_key": os.getenv("DEEPSEEK_API_KEY", ""),
            "base_url": os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com"),
            "model_name": model_name or os.getenv("DEEPSEEK_MODEL", "deepseek-chat"),
        }

    if os.getenv("OPENAI_API_KEY"):
        return {
            "provider": "openai",
            "api_key": os.getenv("OPENAI_API_KEY", ""),
            "base_url": os.getenv("OPENAI_BASE_URL", ""),
            "model_name": model_name or os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        }

    return {
        "provider": "",
        "api_key": "",
        "base_url": "",
        "model_name": model_name or "",
    }


def _extract_json_object(text: str) -> dict[str, Any]:
    """
    从模型输出中提取 JSON 对象。

    兼容：
    - 直接返回 JSON
    - ```json ... ``` 包裹
    - 前后混有解释文本
    - 代码字段正确但 explanation 等字段含字面换行导致 JSON 不合法
    """
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = re.sub(r"^```(?:json)?\s*", "", stripped)
        stripped = re.sub(r"\s*```$", "", stripped)

    try:
        return json.loads(stripped)
    except json.JSONDecodeError:
        pass

    start = stripped.find("{")
    end = stripped.rfind("}")
    if start != -1 and end != -1 and start < end:
        try:
            return json.loads(stripped[start : end + 1])
        except json.JSONDecodeError:
            pass

    # Handle truncated JSON: model stopped generating before writing the closing `}`.
    # Common with json_object mode + whitespace-padding models. Try appending `}`.
    if start != -1 and end == -1:
        tail = stripped[start:].rstrip()
        if tail and not tail.endswith("}"):
            try:
                return json.loads(tail + "}")
            except json.JSONDecodeError:
                pass

    # Fallback: extract key fields via regex when JSON is malformed
    # (common when explanation contains literal newlines but code is valid)
    extracted: dict[str, Any] = {}
    for match in re.finditer(r'"(\w+)"\s*:\s*("(?:[^"\\]|\\.)*")', stripped):
        key = match.group(1)
        try:
            extracted[key] = json.loads(match.group(2))
        except json.JSONDecodeError:
            pass
    if extracted.get("code", "").strip():
        return extracted

    # Rescue: if no "code" key (or empty code) but some value looks like Python code, promote it.
    _PY_STARTERS = ("def ", "import ", "class ", "from ", "async def ", "#")
    for _key in list(extracted.keys()):
        _val = extracted.get(_key, "")
        if isinstance(_val, str) and any(_val.lstrip().startswith(s) for s in _PY_STARTERS):
            extracted["code"] = _val
            return extracted

    # Last resort: try to extract a code block from the raw response.
    code_block = re.search(r"```(?:python)?\s*\n?(.*?)```", stripped, re.DOTALL)
    if code_block:
        return {"code": code_block.group(1).strip()}

    raise ValueError("no valid JSON object found in model output")


def load_json_file(file_path: str | Path) -> Any:
    """读取本地 JSON 文件。"""
    path = Path(file_path)
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def load_cisq_rules(file_path: str | Path) -> list[dict[str, Any]]:
    """
    读取并规范化 CISQ 规则文件。

    兼容两种格式：
    1. 现有框架种子格式：rule_id / dimension / title / ...
    2. 你整理的映射格式：CWE_ID / Characteristic / Description / Refactor_Advice
    """
    raw = load_json_file(file_path)
    if not isinstance(raw, list):
        raise ValueError("CISQ rules file must be a JSON array")

    if raw and "rule_id" in raw[0]:
        return raw

    if raw and "CWE_ID" in raw[0]:
        return normalize_cisq_mapping_rules(raw)

    raise ValueError("unsupported CISQ rules format")


def normalize_cisq_mapping_rules(raw_rules: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    将 CISQ_mapping.json 转换成当前框架统一规则结构。

    输出字段：
    - rule_id
    - dimension
    - title
    - keywords
    - risk_reason
    - repair_pattern
    - priority
    - source

    注意：同一个 CWE_ID 可能在不同 Characteristic 下各出现一次（如 CWE-404 属于
    Performance Efficiency、Reliability、Security 三个维度）。使用 (CWE_ID, dimension)
    作为去重键，保证跨维度条目不会被丢弃。
    """
    normalized: list[dict[str, Any]] = []
    seen_keys: set[str] = set()

    for item in raw_rules:
        cwe_id = str(item.get("CWE_ID", "")).strip()
        if not cwe_id:
            continue

        rule_id = f"CWE-{cwe_id}" if not cwe_id.startswith("CWE-") else cwe_id
        description = str(item.get("Description", "")).strip()
        advice = str(item.get("Refactor_Advice", "")).strip()
        dimension = map_characteristic_to_dimension(str(item.get("Characteristic", "")).strip())

        dedup_key = f"{rule_id}_{dimension}"
        if dedup_key in seen_keys:
            continue
        seen_keys.add(dedup_key)

        normalized.append(
            {
                "rule_id": rule_id,
                "dimension": dimension,
                "title": description or rule_id,
                "keywords": infer_keywords_from_text(description, advice),
                "risk_reason": description or f"{rule_id} related risk",
                "repair_pattern": advice or "Refactor the code according to the rule intent.",
                "priority": infer_priority_from_dimension(dimension),
                "source": "cisq_mapping",
            }
        )

    return normalized


def map_characteristic_to_dimension(characteristic: str) -> str:
    normalized = characteristic.strip().lower().replace(" ", "_")
    mapping = {
        "security": "security",
        "reliability": "reliability",
        "maintainability": "maintainability",
        "performance_efficiency": "performance_efficiency",
    }
    return mapping.get(normalized, normalized or "maintainability")


def infer_priority_from_dimension(dimension: str) -> str:
    if dimension in {"security", "reliability"}:
        return "high"
    if dimension == "performance_efficiency":
        return "medium"
    return "medium"


def infer_keywords_from_text(*texts: str, limit: int = 8) -> list[str]:
    """
    从描述与修复建议中提取轻量关键词。

    这是启发式提取，不追求 NLP 级精准，目标是让 RAR4IS 检索先能工作。
    """
    stop_words = {
        "the",
        "and",
        "for",
        "with",
        "that",
        "this",
        "from",
        "into",
        "your",
        "code",
        "class",
        "method",
        "using",
        "use",
        "ensure",
        "remove",
        "reduce",
        "refactor",
        "logic",
        "data",
        "object",
        "objects",
        "function",
        "functions",
        "control",
        "element",
    }
    words: list[str] = []
    for text in texts:
        for word in re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", text.lower()):
            if word in stop_words:
                continue
            if word not in words:
                words.append(word)
            if len(words) >= limit:
                return words
    return words


def detect_active_dimensions(text: str) -> list[str]:
    """
    根据需求文本做轻量维度激活。

    这是 On-demand Activation 的最小骨架：
    - 数据库 / 输入相关 => security
    - 文件 / 网络 / 连接相关 => reliability
    - 性能关键词 => performance_efficiency
    - maintainability 默认激活
    """
    lowered = text.lower()
    dimensions = {"maintainability"}

    security_keywords = ["database", "sql", "query", "login", "input", "user", "token"]
    reliability_keywords = ["file", "stream", "socket", "network", "connect", "resource"]
    performance_keywords = ["performance", "latency", "throughput", "cache", "loop"]

    if any(keyword in lowered for keyword in security_keywords):
        dimensions.add("security")
    if any(keyword in lowered for keyword in reliability_keywords):
        dimensions.add("reliability")
    if any(keyword in lowered for keyword in performance_keywords):
        dimensions.add("performance_efficiency")

    return sorted(dimensions)


def select_cisq_rules(
    rules: list[dict[str, Any]], requirement_text: str, active_dimensions: list[str]
) -> list[dict[str, Any]]:
    """从 CISQ 规则种子中选出与当前需求最相关的规则。"""
    lowered = requirement_text.lower()
    selected: list[dict[str, Any]] = []

    for rule in rules:
        if rule.get("dimension") not in active_dimensions:
            continue

        keywords = [keyword.lower() for keyword in rule.get("keywords", [])]
        if not requirement_text or any(keyword in lowered for keyword in keywords):
            selected.append(rule)

    # 如果一个维度没有被关键词命中，至少保留该维度的第一条规则，避免空转。
    covered_dimensions = {rule["dimension"] for rule in selected}
    for dimension in active_dimensions:
        if dimension in covered_dimensions:
            continue
        fallback_rule = next(
            (rule for rule in rules if rule.get("dimension") == dimension),
            None,
        )
        if fallback_rule:
            selected.append(fallback_rule)

    return selected


def build_standard_constraints(
    rules: list[dict[str, Any]], active_dimensions: list[str]
) -> dict[str, Any]:
    """把规则列表整理成 Standard_Constraints 结构。"""
    grouped: dict[str, list[dict[str, Any]]] = {dimension: [] for dimension in active_dimensions}
    for rule in rules:
        grouped.setdefault(rule["dimension"], []).append(rule)

    return {
        "dimensions": active_dimensions,
        "rules_by_dimension": grouped,
        "rules": rules,
    }


def heuristic_static_cisq_audit(
    code: str, rules: list[dict[str, Any]]
) -> dict[str, Any]:
    """
    使用可解释的启发式规则做最小静态审判。

    说明：
    - 这是 LLM 静态审判不可用时的本地 fallback；
    - 判断标准偏保守，目的是给 Evaluation 一个可运行骨架。
    """
    lowered = code.lower()
    unresolved_rules: list[str] = []
    findings: list[str] = []

    for rule in rules:
        rule_id = rule["rule_id"]
        title = rule["title"]

        if rule_id == "CWE-89":
            risky = "select " in lowered and ("+" in code or "format(" in lowered or "f\"" in code)
            if risky:
                unresolved_rules.append(rule_id)
                findings.append(f"{rule_id}: 发现疑似字符串拼接 SQL")
        elif rule_id == "CWE-404":
            risky = "open(" in lowered and "with open(" not in lowered
            if risky:
                unresolved_rules.append(rule_id)
                findings.append(f"{rule_id}: 文件资源可能未通过 context manager 关闭")
        elif rule_id == "CWE-476":
            risky = ".strip()" in lowered and "is None" not in lowered and "if not " not in lowered
            if risky:
                unresolved_rules.append(rule_id)
                findings.append(f"{rule_id}: 可能存在空值访问风险")
        elif rule_id == "MAINT-001":
            function_lines = code.count("\n")
            if function_lines > 40:
                unresolved_rules.append(rule_id)
                findings.append(f"{rule_id}: 代码块过长，维护成本偏高")
        elif rule_id == "MAINT-002":
            if code.count("if ") + code.count("for ") + code.count("while ") > 8:
                unresolved_rules.append(rule_id)
                findings.append(f"{rule_id}: 分支/循环数量较多，复杂度偏高")
        elif rule_id == "PERF-001":
            if code.count("for ") >= 2 and "cache" not in lowered:
                unresolved_rules.append(rule_id)
                findings.append(f"{rule_id}: 疑似存在可优化的嵌套循环")
        elif rule_id == "REL-001":
            risky = "requests.get(" in lowered and "timeout=" not in lowered
            if risky:
                unresolved_rules.append(rule_id)
                findings.append(f"{rule_id}: 外部调用缺少 timeout")
        else:
            findings.append(f"{rule_id}: {title} 暂未定义启发式检查，默认待人工复核")

    passed = not unresolved_rules
    summary = "所有启发式 CISQ 检查通过" if passed else "存在未消除的 CISQ 风险"
    return {
        "passed": passed,
        "failed_rule_ids": unresolved_rules,
        "findings": findings,
        "summary": summary,
    }
